# Generated by Django 5.2 on 2025-04-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_created_at'),
        ('courses', '0004_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='users', to='courses.usercourse'),
        ),
    ]
