# Generated by Django 5.2 on 2025-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_courses'),
        ('courses', '0006_purchase_delete_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
