# Generated by Django 5.2 on 2025-04-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_courses'),
        ('courses', '0008_alter_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='courses.purchase'),
        ),
    ]
